

library:
  api:
    base-url: http://localhost:8081/api/v1

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
  task:
    scheduling:
      pool:
        size: 10
    execution:
      pool:
        core-size: 1
        max-size: 10
        queue-capacity: 100
  kafka:
    bootstrap-servers: localhost:9092
